/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionDetail: typeof import('./components/action/ActionDetail.vue')['default']
    ActionsPreview: typeof import('./components/dashboard/ActionsPreview.vue')['default']
    AppBar: typeof import('./components/layout/AppBar.vue')['default']
    AppDrawer: typeof import('./components/layout/AppDrawer.vue')['default']
    AppDrawerItem: typeof import('./components/layout/AppDrawerItem.vue')['default']
    ButtonUser: typeof import('./components/layout/ButtonUser.vue')['default']
    CleaningRequestForm: typeof import('./components/forms/CleaningRequestForm.vue')['default']
    copy: typeof import('./components/extUserActions/ExtOrderDetail copy.vue')['default']
    Detail: typeof import('./components/detail/Detail.vue')['default']
    EmployeeDetail: typeof import('./components/employees/EmployeeDetail.vue')['default']
    EmployeePreviewItem: typeof import('./components/employees/EmployeePreviewItem.vue')['default']
    EmployeesBasicPreview: typeof import('./components/dashboard/EmployeesBasicPreview.vue')['default']
    EmployeesPreview: typeof import('./components/employees/EmployeesPreview.vue')['default']
    ErrorReportForm: typeof import('./components/forms/ErrorReportForm.vue')['default']
    ExtOccurrenceDetail: typeof import('./components/extUserActions/ExtOccurrenceDetail.vue')['default']
    ExtOrderDetail: typeof import('./components/extUserActions/ExtOrderDetail.vue')['default']
    ExtQuestionDetail: typeof import('./components/extUserActions/ExtQuestionDetail.vue')['default']
    ExtReviewDetail: typeof import('./components/extUserActions/ExtReviewDetail.vue')['default']
    ExtUserActionDetail: typeof import('./components/extUserActions/ExtUserActionDetail.vue')['default']
    ExtUserActionPreviewItem: typeof import('./components/extUserActions/ExtUserActionPreviewItem.vue')['default']
    ExtUserActionsPreview: typeof import('./components/extUserActions/ExtUserActionsPreview.vue')['default']
    FAB: typeof import('./components/FAB.vue')['default']
    CheckpointDetail: typeof import('./components/checkpoint/CheckpointDetail.vue')['default']
    CheckpointChipStates: typeof import('./components/checkpoint/CheckpointChipStates.vue')['default']
    CheckpointPreviewItem: typeof import('./components/checkpoint/CheckpointPreviewItem.vue')['default']
    CheckpointsBasicPreview: typeof import('./components/dashboard/CheckpointsBasicPreview.vue')['default']
    CheckpointsPreview: typeof import('./components/checkpoint/CheckpointsPreview.vue')['default']
    ChipState: typeof import('./components/ChipState.vue')['default']
    OccurrenceDetail: typeof import('./components/occurrence/OccurrenceDetail.vue')['default']
    OccurrencePreviewItem: typeof import('./components/occurrence/OccurrencePreviewItem.vue')['default']
    OrderDetail: typeof import('./components/extUserActions/OrderDetail.vue')['default']
    PreviewList: typeof import('./components/preview/PreviewList.vue')['default']
    QuestionDetail: typeof import('./components/extUserActions/QuestionDetail.vue')['default']
    QuickActionForm: typeof import('./components/forms/QuickActionForm.vue')['default']
    ReviewDetail: typeof import('./components/extUserActions/ReviewDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmallPreviewItem: typeof import('./components/preview/SmallPreviewItem.vue')['default']
    SmallPreviewList: typeof import('./components/preview/SmallPreviewList.vue')['default']
  }
}
