/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/layout/AppBar.vue')['default']
    AppDrawer: typeof import('./components/layout/AppDrawer.vue')['default']
    AppDrawerItem: typeof import('./components/layout/AppDrawerItem.vue')['default']
    BuildingDialog: typeof import('./components/layout/BuildingDialog.vue')['default']
    ButtonUser: typeof import('./components/layout/ButtonUser.vue')['default']
    Detail: typeof import('./components/detail/Detail.vue')['default']
    CheckpointDetail: typeof import('./components/checkpoint/CheckpointDetail.vue')['default']
    CheckpointsPreview: typeof import('./components/checkpoint/CheckpointsPreview.vue')['default']
    PersonelPreview: typeof import('./components/Personel/PersonelPreview.vue')['default']
    PreviewItem: typeof import('./components/preview/PreviewItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
