/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/layout/AppBar.vue')['default']
    AppDrawer: typeof import('./components/layout/AppDrawer.vue')['default']
    AppDrawerItem: typeof import('./components/layout/AppDrawerItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
